# Generated by Django 4.0.4 on 2022-08-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0003_delete_carousel_images_logo_carousel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='carousel_img',
        ),
    ]
