# Generated by Django 4.0.4 on 2022-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0005_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyquotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Logoimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
