# Generated by Django 4.0.4 on 2022-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0006_dailyquotes_logoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videolink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdolink', models.CharField(max_length=200)),
                ('memesimg', models.ImageField(upload_to='memepics')),
            ],
        ),
    ]
