# Generated by Django 4.0.4 on 2022-08-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0007_videolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='memesimg',
        ),
    ]
