# Generated by Django 4.0.4 on 2022-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0008_remove_videolink_memesimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addimages', models.ImageField(upload_to='addspics')),
            ],
        ),
    ]
