# Generated by Django 4.0.4 on 2022-08-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiri', '0009_addsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engmemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engmemes', models.ImageField(upload_to='engmemes')),
            ],
        ),
    ]
